# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsctl < Formula
  desc ""
  homepage "https://github.com/prastamaha/awsctl"
  version "0.0.3"

  on_macos do
    url "https://github.com/prastamaha/awsctl/releases/download/v0.0.3/awsctl_0.0.3_darwin_all.tar.gz"
    sha256 "3f69be1ccfdaa9ddbb73dde4a3972ecac30a5d4c7d790b50d8f348f811475b43"

    def install
      bin.install "awsctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/prastamaha/awsctl/releases/download/v0.0.3/awsctl_0.0.3_linux_amd64.tar.gz"
      sha256 "55558ce69a82d0ecdfc2d732ac95431e487b30f239f6df62026da0e28da149b2"
      def install
        bin.install "awsctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/prastamaha/awsctl/releases/download/v0.0.3/awsctl_0.0.3_linux_arm64.tar.gz"
      sha256 "45ad45f36ffe1206fd46201ed81563f9e229ab2c8653f18eddc6ecb59395a509"
      def install
        bin.install "awsctl"
      end
    end
  end
end
